struct ArrayMultiDim
{
    boolean var_array_boolean[8][9][10];
    char var_array_char[8][9][10];
    octet var_array_octet[8][9][10];

    short var_array_short[8][9][10];
    unsigned short var_array_ushort[8][9][10];

    long var_array_long[8][9][10];
    unsigned long var_array_ulong[8][9][10];

    long long var_array_longlong[8][9][10];
    unsigned long long var_array_ulonglong[8][9][10];

    float var_array_float[8][9][10];
    double var_array_double[8][9][10];
};

const long size = 10;
const long size_2 = 20;

struct ArrayMultiDimWithLiterals
{
    char var_array_char[size];
    octet var_array_octet[8][9][10*2];
    short var_array_short[8][9][10+10];
    unsigned short var_array_ushort[size][size][size*10];
    long var_array_long[size][size][size*size];
    unsigned long var_array_ulong[size][size_2][size*size_2];
};
