#include "sequence_basic.idl"

module a_module
{
    typedef sequence<long> LongSeq;

    struct ModuleStruct
    {
        long var_long;
    };

    struct ModuleSequenceBasic
    {
        sequence<unsigned short> var_seq_ushort;
        LongSeq var_alias_seq;
        sequence<ModuleStruct> var_seq_struct;
        SequenceBasic var_sec_basic;
    };
};
