#include "sequence_custom.idl"

module a_module
{
    typedef sequence<SequenceInner> SequenceInnerSeq;

    struct ModuleSequenceCustom
    {
        sequence<SequenceInner> var_seq_seq;
        SequenceInnerSeq var_alias_seq;
    };
};
